### ISSUE TITLE
making health hearts for hp

### ISSUE THREAD

**Issue by atgao** [kodetosuccess/Final-Project#1]
I'm trying to make 5 hearts for the health for Link and the Shadow. To decrease the health, the hearts will slowly become gray each time one of the characters is hit. However, I am having trouble figuring out how to do that. I'm unsure whether or not I should be using an arraylist to create the 5 hearts for Link and the Shadow (10 in total).

**Comment by atgao** [comment]
this is not worth the effort

**Comment by gersteinj** [comment]
Prioritizing more important things is a good choice.
