### ISSUE TITLE
brick breaking game: ball & cannon interaction

### ISSUE THREAD

**Issue by lerazodiaz** [kodetosuccess/Final-Project#13]
1. the ball and cannon glitch sometimes when the ball doesn't fully bounce off the cannon
2. the ball and cannon stays attached and blurs when ball glides through the cannon and the mouse is pressed.

**Comment by atgao** [comment]
you guys originally had 

  if (C1.Touches(c)) {    //if the Cannon touches the cannonball
    c.vel.y = -c.vel.y;    //put the cannonball in the opposite y direction

  }

AND

  if (C1.Touches(c) && mousePressed) {    //if the Cannon touches the cannonball
    c.velxy = -c.vel.x;    //put the cannonball in the oppositex direction

  }

which was causing it to glitch. the x direction of the cannonball doesn't need to be reversed, only the y. it's all fixed now
