### ISSUE TITLE
crocodile game: moving

### ISSUE THREAD

**Issue by lerazodiaz** [kodetosuccess/Final-Project#15]
Moving only occurs when the jumping key is pressed or in either direction. 2 keys aren't able to be pressed at the same time to move the person forward and jump at the same time.

**Comment by atgao** [comment]
i mean i dont think that's as big as a problem as that link will start floating upwards for absolutely no reason... a lot of jumping games have it where you can do an initial jump and only control the x direction... 

but i'm pretty sure if you wanted to do this you would have to do something with && in an if statement

**Comment by atgao** [comment]
okay now the issue is that sometimes link can actually glide across the bottom of the screen if the left/right keys are pressed. but he jumps so ig its okay... we can pretend??
