### ISSUE TITLE
brick game: cannonball

### ISSUE THREAD

**Issue by lerazodiaz** [kodetosuccess/Final-Project#16]
If the cannonball touches the side of the screen in a wrong way, it'll bounce up and down only on the side of the screen.

**Comment by atgao** [comment]
this is because you guys had a code for c.comeback AS WELL AS code to make it bounce off in the opposite direction if it hit a ball. you guys were telling it to do several things if it went off screen which is why the glitch happened. c.comeback() isn't necessary
